### ISSUE TITLE
NoMethodError when not providing a to_ref in case no to_ref argument is given on CLI execution

### ISSUE THREAD

**Issue by j4zz** [iv-mexx/git-releaselog#20]
The stripping of `from_ref_name` and `to_ref_name` from 6b24431d5f7592ce7b171caa9bb635dc28675d1b causes errors in case one of them is `nil`.

For example with the execution of `git-releaselog 0.10.0` (without a to_ref, the expectation being that a releaselog is generated from 0.10.0 up to the current commit):
```
git-releaselog-0.7.1/lib/git-releaselog.rb:12:in `generate_releaselog': undefined method `strip' for nil:NilClass (NoMethodError)
```

In Rails you could think about handling such cases with `NilClass.try?`, but I’m not perfectly sure this is how it should be handled here.

**Comment by iv-mexx** [comment]
Argh I was already trying to add specs for the CLI but did not succeed for now (Don't know yet how to call a CLI Program from a spec) - this would have been caught immediately :disappointed_relieved:

**Comment by j4zz** [comment]
> I was already trying to add specs for the CLI but did not succeed for now (Don't know yet how to call a CLI Program from a spec) 

There are multiple ways to do that in ruby, depending on your needs (interest in the commands output, exit status, subshells, …) . [Here’s a quick overview](http://stackoverflow.com/a/2400/1080651) on stackoverlow, and another [overview explaining even more options](http://mentalized.net/journal/2010/03/08/5-ways-to-run-commands-from-ruby/).
