### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by j4zz** [iv-mexx/git-releaselog#8]
Since [git-changelog](https://rubygems.org/gems/git-changelog/versions/0.9.2) is already taken on rubygems, it would probably be good to change the project's name rather sooner than later.

Some suggestions to get us started (all of them are available on rubygems), but please feel free to pick whatever you like: `gitch`, `git-releaselog`, `git-whatsnew`

**Comment by j4zz** [comment]
git-changelog would also be an option. It better reflects the difference to other git commit message parsers as well.

**Comment by iv-mexx** [comment]
Ich chose to go with `git-releaselog`
